### ISSUE TITLE
Documentation on `email`: defaultFrom, defaultReplyTo, testAddress

### ISSUE THREAD

**Issue by benedictjohannes** [bass3l/strapi-provider-email-smtp#10]
The README documentation of this package documents the following keys under exported `email.settings`:
- `from`
- `replyTo`

These values are not recognized by strapi [v3](https://docs-v3.strapi.io/developer-docs/latest/development/plugins/email.html#configure-your-provider) and [v4](https://docs.strapi.io/developer-docs/latest/plugins/email.html#configure-your-provider), causing the default `noreply@strapi.io` being used as the email `FROM`.

I would suggest updating the README... (or would you like a PR instead?)

**Comment by Mehdi-YC** [comment]
hello , is this solved or not yet , if not , do we have any work around to use smtp ?

**Comment by bass3l** [comment]
@benedictjohannes Thank you, the documentation has been updated.

@SAVE-POlNT There is no problem, only an issue with the documentation, just use `defaultFrom` and `defaultReplyTo` when configuring the provider. If you have other problems, please create a new issue detailing your case, I would be happy to help.

**Comment by rttmax** [comment]
There is an error in the documentation for Strapi 4. 

The settings object should be inside config:

```
module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'strapi-provider-email-smtp',
      providerOptions: {
        host: 'smtp.gmail.com', //SMTP Host
        port: 465   , //SMTP Port
        secure: true,
        username: 'my.username@gmail.com',
        password: 'my.password',
        rejectUnauthorized: true,
        requireTLS: true,
        connectionTimeout: 1,
      },
      settings: {
        defaultFrom: 'my.username@gmail.com',
        defaultReplyTo: 'my.username@gmail.com',
      }, 
    },
  },    
});
```
